language: python
matrix:
  exclude:
    - python: "3.3"
      env: 
        - REQ="django<1.5" DB=postgresql CITIES_LIGHT_CITY_SOURCE=cities1000
        - REQ="django<1.5" DB=mysql CITIES_LIGHT_CITY_SOURCE=cities1000
        - REQ="django<1.5" DB=sqlite CITIES_LIGHT_CITY_SOURCE=cities1000
python:
  - "2.7"
  - "3.3"
env:
  - REQ="django<1.5" DB=postgresql CITIES_LIGHT_CITY_SOURCE=cities1000
  - REQ="django<1.5" DB=mysql CITIES_LIGHT_CITY_SOURCE=cities1000
  - REQ="django<1.5" DB=sqlite CITIES_LIGHT_CITY_SOURCE=cities1000
  - REQ="django<1.6" DB=postgresql
  - REQ="django<1.6" DB=sqlite
  - REQ="django<1.6" DB=mysql
  - REQ="-e git+https://github.com/django/django.git@1.7b2#egg=django" DB=postgresql
  - REQ="-e git+https://github.com/django/django.git@1.7b2#egg=django" DB=mysql
  - REQ="-e git+https://github.com/django/django.git@1.7b2#egg=django" DB=sqlite
  - REQ="django<1.7" DB=postgresql
  - REQ="django<1.7" DB=mysql
  - REQ="django<1.7" DB=sqlite
install:
  - pip install -q $REQ --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - python setup.py install
before_script:
  - "pep8 --ignore=E124,E128 --exclude=tests,south_migrations,migrations,vendor cities_light"
  - mysql -e 'create database cities_light_test;'
  - psql -c 'create database cities_light_test;' -U postgres
script:
  - python setup.py test
  - bash test.sh
